### ISSUE TITLE
[Hung Do] Review React examples

### ISSUE THREAD

**Issue by meovan07** [GraphicDThanh/hung-do-js-training#137]
- PR: [#136](https://github.com/GraphicDThanh/hung-do-js-training/pull/136)
- Description:
  - Examples React:
    - Lifting state up example.
    - Hooks example.
    - Context example.
    - Virtualize long list example.

**Comment by GraphicDThanh** [comment]
https://github.com/GraphicDThanh/hung-do-js-training/pull/136/files
- delete .gitkeep if not need anymore.
- re-check code style css, block css should have empty line between
- still ave warning(red circle) on code changes
- some comments on PR

Tips on view changes: Use checkbox `Viewed` to collapse the file you have review/seen
