### ISSUE TITLE
Refactor code React Basic practice based on comments in public review:

### ISSUE THREAD

**Issue by meovan07** [GraphicDThanh/hung-do-js-training#185]
- [x] Should not disabled ESLint, read more about rules.
- [x] Split code: 
  - Should split file by types
  - Should not split APIs, Utils too small → hard to update general
- [x] Context:
  - Context should not related to UI(event).
  - Check naming convention in Context.
- [x] Checking data flow in Routing:
  - getCategory on fetch API routing → login still fetch data → useless.
- [x] List out test:
  - Use code coverage check code missing test.
- [x] Checking data from BE: Useless
  - Interface change → helper change → validateSchema → this layer belong to BE, should let BE do it
  - Type interface IComment → class IComment or just simply delete it.

**Comment by thanhnguyen-agilityio** [comment]
Please create more issues from this parent issue to make thing done quicker. Each issue go with each MR.

**Comment by meovan07** [comment]
> Please create more issues from this parent issue to make thing done quicker. Each issue go with each MR.

I got it. I'll update as soon as possible.
